// GENERATED by scripts/gen-install-check.mjs — do not edit by hand.
//
// Install check: run checkInstall() from the Apps Script editor (pick it in
// the function list, then Run). The log lists every file of this project
// that is missing or out of date (some of its functions are not found), so
// a file pasted into the wrong place or only half pasted shows at once.
// After pasting fixes, publish a new version of the deployment.

var INSTALL_CHECK_FILES = {
  "ActionTracker":["handleReadActions","readActionsRaw","handleReadLastActionNo","handleAppendAction","handleUpdateAction","handleDeleteAction","handleSendActionEmail","generateActionNo","buildActionRow"],
  "ActivityFeed":["afAllowed_","afFrom_","afIso_","afEquipment_","handleGetActivityFeed"],
  "Auth":["getSessionSecret_","base64UrlDecode_","signPayload_","requireSession_","getSessionOrNull_"],
  "BackfillLastReadings":["handleBackfillLastReadings"],
  "Cache":["vcVersion_","vcBump_","vcKey_","vcGet_","vcPut_","vcRead_"],
  "Code":["doGet","doPost","dispatchWithAccess_","dispatch","jsonOut","readAll","getStartupBundle","getRmsSpmHistory"],
  "Compliance":["readCompliance","parseLabelToYearMonth","handleUpdateCompliance","handleMarkMissingCompliance"],
  "Config":["dataStartRowFor","headerRowFor","worstStatus"],
  "Dashboard":["handleGetVibDashboard"],
  "EmailEvents":["msMailAllowed_","msEventMode_","msSendMail_","msQueueDigest_","sendEmailDigest","installEmailDigest"],
  "EquipmentRegister":["handleUpdateRegisterLimits"],
  "Limits":["lmActive_","lmApply_","lmFor_","handleGetVibLimits","handleSaveVibLimits","handleSetVibPointStatus"],
  "MeasurementTracker":["vtMonthEnd_","vtAddMonths_","vtWorse_","vtCollect_","vtLastMeasured_","vtDueState_","handleGetVibTracker","vtMonths_","vtTracker_","vtAreaGrid_"],
  "ModuleAccess":["maCacheKey_","maNormEmail_","maIsEnforced_","maIsVisitorOnly_","maIsAdmin_","maContractorForOrg_","maGetStatus_","maSetStatus_","maReadRows_","maEnsureSheet_","maEnsureSetup_","maLoadConfig_","maInvalidate_","maResolve_","maAnyTabAtLeast_","maBaseDenial_","maCheckRead_","maCheckWrite_","maFilterSections_","getMyAccess_","getModuleAccessConfig_","maValidPerson_","maAddPeople_","maRemovePerson_","maNormTabChange_","maSetTabLevels_","maSetTabLevel_","maResponsibleEmails_","maTechnicians_","maDescribeChange_","maHandleAdminPost_","maToday_","maYmd_","maDelegations_","maDelegationState_","maSideFor_","maResponsibility_","maResponsibleNow_","maCoveredNow_","maNobodyResponsibleFor_","maPeopleWith_","maDelegationNotify_","maGetMyDelegations_","maCreateDelegation_","maEndDelegation_","maHandleSelfAction_","maTeamScope_","maCoveringOn_","maTeamHistory_"],
  "ModuleAccessConfig":["maVibGenericSheetTabs_"],
  "ModuleSettings":["vsApplySettings_","vsTargets_","vsPhrases_","msCanEdit_","msStamp_","msStamps_","msEmail_","msStatus_","vsLimitsSummary_","handleGetModuleSettings","handleSaveModuleSettings"],
  "MyWork":["vmwSection_","handleGetMyWork"],
  "PlatformEquipment":["peKey_","peCacheGet_","peCachePut_","peMaster_","peSig_","pePlatform_","peEquipmentIdProblem_","peApplyToPoints_","peApplyToMachines_","peCollect_","peBell_","peOwnerEmail_","peCheckSheet_","peRun_","handleGetIdCheck","peForget_","handleMarkIdCheck","idCheckDaily","installIdCheck","psaRank_","psaClamp_","psaRead_","psaLevel_"],
  "Readings":["rdInput_","handleSaveVibReadings","handleGetVibEquipmentSummary"],
  "RmsData":["handleUpsertLastRMS","handleDeleteLastRMS"],
  "Routes":["vrRoles_","vrOut_","vrSuggestions_","handleGetVibRoutes","handleGetVibRoute","vrCanSee_","vrNotify_","handleCreateVibRoute","vrFind_","vrWrite_","handleSaveVibRouteProgress","handleVibRouteTransition","handleDismissVibSuggestion"],
  "Settings":["handleReadConfig","readConfigRaw","handleSaveConfig"],
  "SpmData":["handleUpsertLastSPM","handleDeleteLastSPM"],
  "TeamHistory":["vteamDays_","teamCollect_"],
  "Triggers":["onEdit"],
  "Utils":["readSheet","handleAppend","handleUpdateRow","handleDeleteRow","findRowIndex","getAllRowsForEquip","updateMachineStatusCol","recalcMachineStatus"],
  "VibActions":["vaOut_","vaWrite_","vaNextId_","vaPointsText_","vaApplyFindings_","handleGetVibActions","handleGetVibActionHistory","vaFind_","handleSaveVibAction","handleVibActionTransition"],
  "VibNotifications":["vnAdd_","handleGetVibNotifications","handleMarkVibNotificationsRead","maNotify_"],
  "VibRegistry":["readVibRegistry"],
  "VibrationLog":["vlLocked_","vlTz_","vlDate_","vlMonth_","vlToday_","vlNowIso_","vlAddDays_","vlMonthEnd_","vlNum_","vlBand_","vlLevel_","vlYmdFast_","vlRead_","vlReadSheet_","vlEnsure_","vlRowFrom_","vlAudit_","vlActor_","vlMasterData_","vlAreaOf_","vlScopeOf_","vlScopes_","vlDueDate_","vlReportStatus_","vlReportOut_","handleGetVibLog","vlEntryOut_","handleGetVibReport","handleGetVibEquipmentHistory","handleGetVibEntriesFor","vlFindReport_","vlWriteReport_","handleSaveVibReport","handleSaveVibEntries","vlSaveRecommendations_","vlRecommendations_","vlCounts_","vlWriteCoverage_","handleVibReportTransition","vlNotify_"]
};

function checkInstall() {
  var g = (function () { return this; })() || globalThis;
  var missing = [], old = [], ok = 0;
  Object.keys(INSTALL_CHECK_FILES).forEach(function (file) {
    var names = INSTALL_CHECK_FILES[file];
    var gone = names.filter(function (n) { return typeof g[n] !== 'function'; });
    if (gone.length === names.length) missing.push(file);
    else if (gone.length) old.push(file + ' (not found: ' + gone.slice(0, 5).join(', ') + (gone.length > 5 ? ' …' : '') + ')');
    else ok++;
  });
  var lines = ['vibration-analysis: ' + ok + ' of ' + Object.keys(INSTALL_CHECK_FILES).length + ' files OK.'];
  if (missing.length) lines.push('MISSING — add these files: ' + missing.join(', '));
  if (old.length) lines.push('OUT OF DATE — paste these files again: ' + old.join('; '));
  if (!missing.length && !old.length) lines.push('Everything is in place. Remember to publish a new version of the deployment.');
  var text = lines.join('\n');
  Logger.log(text);
  return text;
}
