// GENERATED by scripts/gen-install-check.mjs — do not edit by hand.
//
// Install check: run checkInstall() from the Apps Script editor (pick it in
// the function list, then Run). The log lists every file of this project
// that is missing or out of date (some of its functions are not found), so
// a file pasted into the wrong place or only half pasted shows at once.
// After pasting fixes, publish a new version of the deployment.

var INSTALL_CHECK_FILES = {
  "ActionRegistry":["readActionRegistry"],
  "ActionWorkflow":["normActionStatus_","ensureActionWorkflowHeaders_","actionForSample_","sampleActionTakenMsg_","asDate_","actionDueEnd_","isActionRowOverdue_","isActionEngineer_","columnLetter_","actionKeyLabel_","actionContractor_","guardActionTrackerSave_","writeActionDueFields_","rescheduleAction","findActionRow_","getActionContractor_","setActionCells_","requestActionClosure","decideActionClosure","closeAction","nextActionAcNo_","latestOilChangeDate_","createDraftAction_","lastAgreedActionForLp_","openActionsForLp_","applyLabResultRule_","applyLeakageRule_","migrateActionStatusesPhase2","migrateActionStatusesPhase2DryRun"],
  "ActivityFeed":["afAllowed_","afFrom_","afIso_","afEquipment_","handleGetActivityFeed"],
  "AlternativeOils":["ensureServerHeaders_","normOil_","sameOil_","oilLabel_","approvedOilsFor_","currentOilByLp_","labelMatchesOption_","oilPlanFor_","oilPlanContext_","oilPlanForLp_","getOilPlan","checkOilUsed_","routineItemOil_","productById_","setOilEquivalent"],
  "AuditLog":["recordAudit_","getAuditTrail"],
  "Auth":["checkSecret_","getSessionSecret_","base64UrlDecode_","signPayload_","requireSession_","checkAuth_"],
  "Code":["doGet","doPost","doPostInner_"],
  "DailyNotifications":["notifySentKeys_","markNotified_","isoDay_","weekKey_","lpsOnOpenRoutes_","lpsDueSoon_","runDailyOilNotifications","installDailyOilNotificationsTrigger"],
  "Dashboard":["readAll","getStartupBundle","getDashboard","getEquipmentData","searchEquipment","getChanges","filterChangedSince","getDashboardSettings_","updateDashboardSettings_"],
  "EmailEvents":["msMailAllowed_","msEventMode_","msSendMail_","msQueueDigest_","sendEmailDigest","installEmailDigest"],
  "EquipmentRegistry":["invalidateLpContractorMap_","getLpContractorMap_","readLpContractorMap_","readEquipmentRegistry","squashReportId_","learnReportEquipmentId_"],
  "InAppNotifications":["recordInAppNotification_","recordInAppNotificationForEach_","getInAppNotifications_","markInAppNotificationRead_","markAllInAppNotificationsRead_","maNotify_"],
  "LabReports":["ensureLabHeaders_","ensureLabInfoHeaders_","labInfoText_","writeLabReportInfo_","findSampleRowById_","fillLabReportInfo_","findSampleRow_","labStatusOf_","sampleLabel_","getSampleContractor_","normLabCell_","guardLabReportEdit_","onLabReportSaved_","validateLabReport","returnLabReport","normSampleId_","sampleIdExists_"],
  "Managers":["routeOverdueFrom_","isRouteRowOverdue_","escalateLongOverdue_","getTeamWorkload"],
  "ModuleAccess":["maCacheKey_","maNormEmail_","maIsEnforced_","maIsVisitorOnly_","maIsAdmin_","maContractorForOrg_","maGetStatus_","maSetStatus_","maReadRows_","maEnsureSheet_","maEnsureSetup_","maLoadConfig_","maInvalidate_","maResolve_","maAnyTabAtLeast_","maBaseDenial_","maCheckRead_","maCheckWrite_","maFilterSections_","getMyAccess_","getModuleAccessConfig_","maValidPerson_","maAddPeople_","maRemovePerson_","maNormTabChange_","maSetTabLevels_","maSetTabLevel_","maResponsibleEmails_","maTechnicians_","maDescribeChange_","maHandleAdminPost_","maToday_","maYmd_","maDelegations_","maDelegationState_","maSideFor_","maResponsibility_","maResponsibleNow_","maCoveredNow_","maNobodyResponsibleFor_","maPeopleWith_","maDelegationNotify_","maGetMyDelegations_","maCreateDelegation_","maEndDelegation_","maHandleSelfAction_","maTeamScope_","maCoveringOn_","maTeamHistory_"],
  "ModuleAccessConfig":["maOilGenericSheetTabs_","maImportLegacyPeople_"],
  "ModuleResponsibilities":["getModuleResponsibilities_","getModuleResponsibleEmail_","setModuleResponsibility_"],
  "ModuleSettings":["msCanEdit_","msStamp_","msStamps_","msEmail_","msStatus_","msTargets_","handleGetModuleSettings","msIntervalProblem_","handleSaveModuleSettings"],
  "MyWork":["myWorkRoles_","fmtDay_","section_","getMyWork"],
  "Notifications":["getNotificationSettings_","updateNotificationSettings_","sendNotificationEmail_","getNotifyReviewers_","looksLikeEmail_","formatDateForEmail_","notifyRoutineAssigned_","notifyRoutineSubmitted_","notifyRoutineReturned_","notifyRoutineCreatedByAcc_","notifyRoutineApproved_","sendAgingActionsDigest","sendLowStockDigest"],
  "OilChanges":["logOilChangeEvent","oilBrandTypeFor_","findRegistryEntryForOilChange_","intervalMonthsForOilChange_","addMonths_","getOilChangesForLp"],
  "OilInventory":["getOilInventory","productMovementStats_","getProductContractor_","getOilInventoryForecast","monthKey_","getOilInventoryConsumption","getOilInventoryMovements","getAllOilInventoryMovements","addOilProduct","copyStockFormulas_","updateOilProduct","findInventoryProductRow_","findMatchingProduct_","tryAutoDeductInventory_","productStocksFromLog_","productStockFromLog_","findProductRow_","productLabel_","checkLowStockAfterMovement_","setProductLowStockLevel","logOilMovement"],
  "PlatformEquipment":["peKey_","peCacheGet_","peCachePut_","peMaster_","peSig_","pePlatform_","peEquipmentIdProblem_","peApplyToRegistry_","peLpIds_","peCollect_","peBell_","peOwnerEmail_","peCheckSheet_","peRun_","handleGetIdCheck","peForget_","handleMarkIdCheck","idCheckDaily","installIdCheck","psaRank_","psaClamp_","psaRead_","psaLevel_"],
  "Rbac":["hasPermission_","requirePermission_","requireAdmin_","isRouteEngineerFor_","requireRouteEngineer_","isAccEngineer_","requireAccEngineer_","getContractorScope_","filterRowsByLpContractor_","filterTrackerRowsByLpContractor_","requireContractorMatch_","requireLpContractorMatch_","resolveLpContractor_","genericWriteLpId_","resolveRowLpId_","lockEquipmentRegistryContractor_"],
  "ReadCache":["rcVersion_","rcBump_","rcKey_","rcGet_","rcPut_"],
  "RouteTemplates":["readRouteTemplates","createRouteTemplate","getTemplateContractor_","setRouteTemplateStatus","deleteRouteTemplate","generateDueRouteInstances","generateDueRouteInstancesInner_","computeDueLpIds_","intervalMonthsForRoute_","countMatchingEquipment_","classifyDueStatus_","getRoutinesOverview","getRoutineCompletionTrend","advanceByFrequency_"],
  "Routines":["normRouteStatus_","normRoutineRow_","ensureRoutinePhase1Headers_","isRouteReturnedRow_","routineStatusAt_","sameDay_","migrateRouteStatusesPhase1","migrateRouteStatusesPhase1DryRun","getRoutines","getRoutine","getRoutineContractor_","getRoutineIdForItem_","getRoutineItems","createRoutine","assignRoutineTechnician","updateRoutine","rescheduleRoutine","setRoutineStatus","deleteRoutine","submitRoutineItem","submitRoutine","approveRoutine","returnRoutine","addRoutineComment","getRoutesForLp"],
  "SampleOverdue":["intervalMonthsForSampling_","sampleAgeMonths_","sampleStatusLabel_","sampleDueDate_","sampleDigestAlreadySentThisMonth_","markSampleDigestSent_","checkSampleOverdueAndNotify"],
  "SampleTracker":["findOrCreateMonthColumn_","updateSampleTrackerMonthly"],
  "SheetTriggers":["onEdit","logDirectEditIfTracked_","protectDataSheetsFromDirectEdits"],
  "Suggestions":["suggestionSheet_","suggestionWorkTypes_","readSuggestionRows_","suggestionToObject_","getSuggestions","setSuggestionCells_","syncSuggestionsForAction_","convertSuggestions_","reopenSuggestionsForRoutine_"],
  "TeamHistory":["teamDayDiff_","teamCollect_"],
  "TopUps":["logOilTopUp_","getTopUpsForLp","getAllTopUps"],
  "Utils":["outputResult_","jsonOut","logError","dataStartRowFor","readSheet","canonicalContractor_","invalidateDashboardCache","invalidateRoutinesOverviewCache","compareDates","toComparableDate","getPaginated","findRowIndex","updateRow","deleteRow","appendRow","stampLastModified","hasConflict_","normalizeMonthHeader"]
};

function checkInstall() {
  var g = (function () { return this; })() || globalThis;
  var missing = [], old = [], ok = 0;
  Object.keys(INSTALL_CHECK_FILES).forEach(function (file) {
    var names = INSTALL_CHECK_FILES[file];
    var gone = names.filter(function (n) { return typeof g[n] !== 'function'; });
    if (gone.length === names.length) missing.push(file);
    else if (gone.length) old.push(file + ' (not found: ' + gone.slice(0, 5).join(', ') + (gone.length > 5 ? ' …' : '') + ')');
    else ok++;
  });
  var lines = ['oil-lubrication: ' + ok + ' of ' + Object.keys(INSTALL_CHECK_FILES).length + ' files OK.'];
  if (missing.length) lines.push('MISSING — add these files: ' + missing.join(', '));
  if (old.length) lines.push('OUT OF DATE — paste these files again: ' + old.join('; '));
  if (!missing.length && !old.length) lines.push('Everything is in place. Remember to publish a new version of the deployment.');
  var text = lines.join('\n');
  Logger.log(text);
  return text;
}
