// Routine workflow: create / submit item / submit / approve / comment, and
// reading ROUTINES + OA_ROUTINE_ITEMS. Split out of the old monolithic
// Code.js (see docs/oil-lubrication-migration-notes.md).



// ─── Routines (Step 4) ────────────────────────────────────────────────────
//
// ROUTINES columns: 0 RoutineId, 1 CreatedBy, 2 AssignedTo, 3 Contractor,
// 4 CreatedDate, 5 Status, 6 SubmittedDate, 7 ApprovedBy, 8 ApprovedDate,
// 9 ACC_Comment, 10 ACC_CommentBy, 11 ACC_CommentDate. "Solid app round"
// addition (see docs/oil-lubrication-migration-notes.md): 12 RouteName,
// 13 RouteType ("Oil Change"|"Sampling" — applies to every item on the
// route, replacing the old per-item type picker), 14 DueDate,
// 15 SourceTemplateId (blank for a manually-created routine; set to a
// ROUTINE_TEMPLATES TemplateId for one generated by
// generateDueRouteInstances — see RouteTemplates.js). Status also gained
// "Unassigned": a recurring template generates a routine with no
// AssignedTo yet, and assignRoutineTechnician (below) is the only way to
// move it to "Assigned". Patch 18 (plant-readiness pass): 16 Reason —
// blank except for a RouteType="Emergency Top Up" routine, where it's
// required (why the top-up was needed — leakage, low level, etc.). An
// Emergency Top Up routine is always single-equipment (exactly one item),
// confirmed directly by the user, unlike Oil Change/Sampling routes which
// can cover many LPs. 17 Area — added for the Routines tab's own "Area"
// filter/chart, which a standalone routine always reported blank for
// before this (getRoutinesOverview had nowhere to read it from — see
// RouteTemplates.js's own comment); derived client-side from the selected
// equipment (NewRoutine.jsx) and never auto-populated for a template-
// generated routine (that one's own Area lives on its ROUTINE_TEMPLATES
// row instead, same as RouteType/Frequency/OilType already do — a
// generated routine's raw sheet row is genuinely shorter than this and
// simply has nothing written past SourceTemplateId, which is fine, Sheets
// rows don't need to be rectangular). 18 Duration — days of grace after
// DueDate before a standalone routine counts as Overdue (confirmed
// directly by the user: "Due date and Duration on days, if its started
// during this duration so will be on schedule"). No separate "work
// actually started" timestamp exists anywhere in this schema, so this is
// implemented as a window on the same today-vs-date comparison
// classifyDueStatus_ already does everywhere else, not literal start-time
// tracking — see getRoutinesOverview's own comment in RouteTemplates.js.
// Blank/0 for a routine created before this existed behaves exactly like
// the old no-grace-period logic (dueDate + 0 = dueDate).
// OA_ROUTINE_ITEMS columns: 0 RoutineItemId, 1 RoutineId, 2 LP_ID,
// 3 ItemType, 4 RequiredOilType, 5 Implemented, 6 NotImplementedReason,
// 7 ActualDate, 8 ActualQuantity, 9 SampleTaken, 10 CreatedDate,
// 11 ModifiedDate. Both sheets have a plain header at row 1, data at row
// 2+ (dataStartRowFor's standard default already covers them).
//
// The client generates RoutineId/RoutineItemId itself (not this backend) —
// unlike logOilChangeEvent's server-generated EventId, createRoutine needs
// to write BOTH the routine row and its item rows as one logical unit, and
// a client-supplied id makes write-verification exact (find by id) instead
// of guessing "the newest matching routine", which isn't safe if two get
// created around the same time.

// ─── Phase 1: route statuses ─────────────────────────────────────────────
//
// Draft → Assigned → In Progress → Waiting Approval → Confirmed, with
// Paused and Cancelled alongside (Overdue is computed, never stored).
// Rows written before Phase 1 carry the old names; normRouteStatus_ maps
// them on every read and every comparison, so old rows and old offline
// work keep working until migrateRouteStatusesPhase1 rewrites the column.
var ROUTE_STATUS = {
  DRAFT: "Draft",
  ASSIGNED: "Assigned",
  IN_PROGRESS: "In Progress",
  WAITING: "Waiting Approval",
  CONFIRMED: "Confirmed",
  PAUSED: "Paused",
  CANCELLED: "Cancelled"
};
var LEGACY_ROUTE_STATUS = {
  "Unassigned": "Draft",
  "InProgress": "In Progress",
  "Submitted": "Waiting Approval",
  "Approved": "Confirmed"
};
// A route is Overdue once it isn't submitted by DueDate + Duration + this.
var ROUTE_OVERDUE_GRACE_DAYS = 7;

// Phase 1 columns (0-based), after 18 Duration:
//   19 ReturnReason, 20 ReturnedBy, 21 ReturnedDate — last "return for
//      correction"; the Returned badge shows while ReturnedDate is on or
//      after SubmittedDate and the route is back with the technician.
//   22 OriginalDueDate (set by the first reschedule only), 23 RescheduleReason,
//   24 RescheduledBy, 25 RescheduledDate — the latest reschedule; every
//      reschedule is also written to the Activity log with both dates.
var ROUTINE_COLS = 26;
var ROUTINE_PHASE1_HEADERS = ["ReturnReason", "ReturnedBy", "ReturnedDate", "OriginalDueDate", "RescheduleReason", "RescheduledBy", "RescheduledDate"];

function normRouteStatus_(status) {
  var s = String(status || "").trim();
  return LEGACY_ROUTE_STATUS[s] || s;
}

// Same width for every row, status in its new name — the client parsers
// read fixed positions (ItemsTotal/ItemsDone sit right after this width).
function normRoutineRow_(row) {
  var out = row.slice(0, ROUTINE_COLS);
  while (out.length < ROUTINE_COLS) out.push("");
  out[5] = normRouteStatus_(out[5]);
  return out;
}

function ensureRoutinePhase1Headers_(sheet) {
  var range = sheet.getRange(1, 20, 1, ROUTINE_PHASE1_HEADERS.length);
  var current = range.getValues()[0];
  var missing = current.some(function (v) { return !String(v || "").trim(); });
  if (missing) range.setValues([ROUTINE_PHASE1_HEADERS]);
}

// Returned for correction and not yet resubmitted (ReturnedDate on/after
// SubmittedDate, route back with the technician).
function isRouteReturnedRow_(row, status) {
  var returned = row[21] ? new Date(row[21]) : null;
  if (!returned || isNaN(returned.getTime())) return false;
  if ([ROUTE_STATUS.ASSIGNED, ROUTE_STATUS.IN_PROGRESS, ROUTE_STATUS.PAUSED].indexOf(status) === -1) return false;
  var submitted = row[6] ? new Date(row[6]) : null;
  return !submitted || isNaN(submitted.getTime()) || returned.getTime() >= submitted.getTime();
}

function routineStatusAt_(sheet, rowIdx) {
  return normRouteStatus_(sheet.getRange(rowIdx, 6).getValue());
}

function sameDay_(a, b) {
  if (!a || !b) return false;
  var x = new Date(a), y = new Date(b);
  if (isNaN(x.getTime()) || isNaN(y.getTime())) return false;
  return x.getFullYear() === y.getFullYear() && x.getMonth() === y.getMonth() && x.getDate() === y.getDate();
}

// Run once from the Apps Script editor when Phase 1 is released (after the
// sheet backup): rewrites old status names in ROUTINES to the new ones and
// adds the new column headers. Safe to run again — already-converted rows
// are left as they are. Pass true to only count what would change.
function migrateRouteStatusesPhase1(dryRun) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName("ROUTINES");
  if (!sheet) return { status: "error", message: "ROUTINES sheet not found" };
  var last = sheet.getLastRow();
  var counts = {};
  var changed = 0;
  if (last >= 2) {
    var range = sheet.getRange(2, 6, last - 1, 1);
    var vals = range.getValues();
    for (var i = 0; i < vals.length; i++) {
      var from = String(vals[i][0] || "").trim();
      var to = normRouteStatus_(from);
      if (to !== from) {
        counts[from + " → " + to] = (counts[from + " → " + to] || 0) + 1;
        vals[i][0] = to;
        changed++;
      }
    }
    if (!dryRun && changed) range.setValues(vals);
  }
  if (!dryRun) {
    ensureRoutinePhase1Headers_(sheet);
    invalidateRoutinesOverviewCache();
  }
  var result = { status: "ok", dryRun: !!dryRun, changed: changed, counts: counts };
  Logger.log(JSON.stringify(result));
  return result;
}

function migrateRouteStatusesPhase1DryRun() {
  return migrateRouteStatusesPhase1(true);
}


// Progress (items done / total) per routine, so the list can show it
// without an N+1 fetch (one getRoutineItems call per routine) — reads
// OA_ROUTINE_ITEMS once here and appends two columns (ItemsTotal,
// ItemsDone) to each ROUTINES row instead.
function getRoutines() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var rows = readSheet(ss, "ROUTINES", true);
  var itemRows = readSheet(ss, "OA_ROUTINE_ITEMS", true);
  var counts = {}; // routineId -> { total, done }
  for (var i = 0; i < itemRows.length; i++) {
    var routineId = String(itemRows[i][1] || "").trim();
    if (!routineId) continue;
    if (!counts[routineId]) counts[routineId] = { total: 0, done: 0 };
    counts[routineId].total++;
    if (String(itemRows[i][5] || "").trim() === "Yes") counts[routineId].done++;
  }
  var enriched = rows.map(function(r) {
    var c = counts[String(r[0] || "").trim()] || { total: 0, done: 0 };
    return normRoutineRow_(r).concat([c.total, c.done]);
  });
  return { routines: enriched, count: enriched.length };
}


// Single-routine lookup (Routines tab improvement pass — "opening the
// routine from table taking too much time"). RoutineDetail.jsx used to
// call the full getRoutines() above just to find one row by id — that
// reads the ENTIRE ROUTINES sheet AND the entire OA_ROUTINE_ITEMS sheet
// (to join on every OTHER routine's own item counts too), every single
// time anyone opened any one routine. The detail page already fetches
// its own item list separately (getRoutineItems) and computes its own
// done-count client-side, so it never actually needed that join — this
// skips it entirely and returns just the one row.
function getRoutine(routineId, scope) {
  var id = String(routineId || "").trim();
  if (!id) return { error: "routineId is required" };
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var rows = readSheet(ss, "ROUTINES", true);
  for (var i = 0; i < rows.length; i++) {
    if (String(rows[i][0] || "").trim() !== id) continue;
    if (scope && String(rows[i][3] || "").trim() !== scope) return { error: "Routine not found" };
    return { routine: normRoutineRow_(rows[i]) };
  }
  return { error: "Routine not found" };
}


// For contractor-scope checks on an action that targets an existing
// routine (submit item, submit, approve, comment, assign) — null if the
// routine doesn't exist (the action's own findRowIndex call will report
// "Routine not found" right after, this is just for the scope check that
// runs before it).
function getRoutineContractor_(routineId) {
  var id = String(routineId || "").trim();
  if (!id) return null;
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var rows = readSheet(ss, "ROUTINES", true);
  for (var i = 0; i < rows.length; i++) {
    if (String(rows[i][0] || "").trim() === id) return String(rows[i][3] || "").trim();
  }
  return null;
}


// For submitRoutineItem's scope check — that action only carries a
// routineItemId, not the routineId a contractor-scope check needs, so this
// looks it up first (before any write happens).
function getRoutineIdForItem_(routineItemId) {
  var id = String(routineItemId || "").trim();
  if (!id) return null;
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var rows = readSheet(ss, "OA_ROUTINE_ITEMS", true);
  for (var i = 0; i < rows.length; i++) {
    if (String(rows[i][0] || "").trim() === id) return String(rows[i][1] || "").trim();
  }
  return null;
}


function getRoutineItems(routineId) {
  var id = String(routineId || "").trim();
  if (!id) return { items: [] };
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var rows = readSheet(ss, "OA_ROUTINE_ITEMS", true).filter(function(r) {
    return String(r[1] || "").trim() === id;
  });
  return { items: rows, count: rows.length };
}


function createRoutine(ss, data) {
  var routineId = String(data.routineId || "").trim();
  if (!routineId) return { error: "routineId is required" };
  // Phase 1: no technician yet = Draft (assigned later).
  var assignedTo = String(data.assignedTo || "").trim();
  var routeType = String(data.routeType || "").trim();
  if (routeType !== "Oil Change" && routeType !== "Sampling" && routeType !== "Emergency Top Up") {
    return { error: "routeType must be 'Oil Change', 'Sampling', or 'Emergency Top Up'" };
  }
  var routeName = String(data.routeName || "").trim();
  if (!routeName) return { error: "routeName is required" };
  var items = Array.isArray(data.items) ? data.items : [];
  if (items.length === 0) return { error: "At least one lubrication point is required" };

  var reason = String(data.reason || "").trim();
  if (routeType === "Emergency Top Up") {
    if (items.length !== 1) return { error: "An Emergency Top Up routine covers exactly one piece of equipment" };
    if (!reason) return { error: "A reason is required for an Emergency Top Up" };
  }

  var now = new Date();
  var dueDate = data.dueDate ? new Date(data.dueDate) : "";
  if (dueDate && isNaN(dueDate.getTime())) dueDate = "";
  var routineRow = [
    routineId,
    data.createdBy || "",
    assignedTo,
    data.contractor || "",
    now,
    assignedTo ? ROUTE_STATUS.ASSIGNED : ROUTE_STATUS.DRAFT,
    "", // SubmittedDate
    "", // ApprovedBy
    "", // ApprovedDate
    "", // ACC_Comment
    "", // ACC_CommentBy
    "", // ACC_CommentDate
    routeName,
    routeType,
    dueDate,
    "", // SourceTemplateId — blank for a manually-created routine
    reason,
    String(data.area || "").trim(),
    Math.max(0, parseInt(data.duration, 10) || 0),
  ];
  appendRow(ss, "ROUTINES", routineRow);

  // Whole-route type: every item gets the same itemType, derived from
  // routeType rather than picked per point (see the header comment above).
  var itemType = routeType === "Sampling" ? "Sample" : routeType === "Emergency Top Up" ? "TopUp" : "Change";
  for (var i = 0; i < items.length; i++) {
    var item = items[i];
    var itemRow = [
      item.routineItemId || ("RI-" + Utilities.getUuid()),
      routineId,
      item.lpId || "",
      itemType,
      item.requiredOilType || "",
      "", // Implemented
      "", // NotImplementedReason
      "", // ActualDate
      "", // ActualQuantity
      "", // SampleTaken
      now,
      "", // ModifiedDate — filled by appendRow's stampLastModified
    ];
    appendRow(ss, "OA_ROUTINE_ITEMS", itemRow);
  }

  if (assignedTo) {
    try {
      notifyRoutineAssigned_(routineId, routeName, assignedTo, dueDate);
    } catch (e) {
      logError("notifyRoutineAssigned_:createRoutine", e, { routineId: routineId });
    }
    // Phase 1: an ACC Engineer's route goes straight to the technician;
    // the contractor's responsible engineers are informed.
    if (data.createdByAcc) {
      try {
        notifyRoutineCreatedByAcc_(routineId, routeName, data.contractor || "", assignedTo, data.actingUser || data.createdBy || "", dueDate);
      } catch (e) {
        logError("notifyRoutineCreatedByAcc_", e, { routineId: routineId });
      }
    }
  }

  return { status: "ok", routineId: routineId, routineStatus: assignedTo ? ROUTE_STATUS.ASSIGNED : ROUTE_STATUS.DRAFT };
}


// Only path from "Unassigned" (a recurring-template-generated routine with
// no technician yet) to "Assigned" — see RouteTemplates.js's
// generateDueRouteInstances for how a routine gets into Unassigned in the
// first place.
function assignRoutineTechnician(ss, data) {
  var routineId = String(data.routineId || "").trim();
  if (!routineId) return { error: "routineId is required" };
  var assignedTo = String(data.assignedTo || "").trim();
  if (!assignedTo) return { error: "assignedTo is required" };
  var sheet = ss.getSheetByName("ROUTINES");
  if (!sheet) return { error: "ROUTINES sheet not found" };
  var rowIdx = findRowIndex(sheet, [0], [routineId], dataStartRowFor("ROUTINES"));
  if (rowIdx === -1) return { error: "Routine not found" };
  var currentStatus = routineStatusAt_(sheet, rowIdx);
  if (currentStatus !== ROUTE_STATUS.DRAFT) return { error: "Only a Draft route can be assigned this way" };
  sheet.getRange(rowIdx, 3).setValue(assignedTo);
  sheet.getRange(rowIdx, 6).setValue(ROUTE_STATUS.ASSIGNED);

  try {
    var routeName = sheet.getRange(rowIdx, 13).getValue();
    var dueDate = sheet.getRange(rowIdx, 15).getValue();
    notifyRoutineAssigned_(routineId, routeName, assignedTo, dueDate);
  } catch (e) {
    logError("notifyRoutineAssigned_:assignRoutineTechnician", e, { routineId: routineId });
  }

  return { status: "ok" };
}


// Edit Routine (Routines tab improvement pass): the one gap this app had
// no path for at all — nothing could ever change a routine's own name,
// technician, due date, area, or (for an Emergency Top Up) its reason
// after creation. Deliberately does NOT touch RouteType or the LP/item
// list — OA_ROUTINE_ITEMS rows (and any checklist progress already saved
// against them) are keyed off the routine as created, and letting the
// equipment list change out from under in-progress checklist entries is a
// different, riskier feature than a straightforward field edit. Locked
// once Approved, same as everything else about a routine at that point —
// it's the final sign-off, not a draft.
//
// Phase 1: the due date is changed only through Reschedule (recorded with
// a reason). An edit that still sends a dueDate — an older app version or
// queued offline work — is accepted only when the date is unchanged.
// Giving a Draft route a technician here moves it to Assigned.
function updateRoutine(ss, data) {
  var routineId = String(data.routineId || "").trim();
  if (!routineId) return { error: "routineId is required" };
  var sheet = ss.getSheetByName("ROUTINES");
  if (!sheet) return { error: "ROUTINES sheet not found" };
  var rowIdx = findRowIndex(sheet, [0], [routineId], dataStartRowFor("ROUTINES"));
  if (rowIdx === -1) return { error: "Routine not found" };
  var currentStatus = routineStatusAt_(sheet, rowIdx);
  if (currentStatus === ROUTE_STATUS.CONFIRMED) return { error: "Cannot edit a confirmed route" };

  var routeName = String(data.routeName || "").trim();
  if (!routeName) return { error: "routeName is required" };
  var assignedTo = String(data.assignedTo || "").trim();
  if (!assignedTo && currentStatus !== ROUTE_STATUS.DRAFT) return { error: "assignedTo is required" };
  var routeType = String(sheet.getRange(rowIdx, 14).getValue() || "").trim();
  var reason = String(data.reason || "").trim();
  if (routeType === "Emergency Top Up" && !reason) return { error: "A reason is required for an Emergency Top Up" };

  if (data.dueDate !== undefined && data.dueDate !== null && String(data.dueDate) !== "") {
    var currentDue = sheet.getRange(rowIdx, 15).getValue();
    if (!sameDay_(currentDue, data.dueDate)) {
      return { error: "Use Reschedule to change the due date, so the reason is recorded." };
    }
  }

  var previousAssignee = String(sheet.getRange(rowIdx, 3).getValue() || "").trim();
  sheet.getRange(rowIdx, 3).setValue(assignedTo);   // AssignedTo
  sheet.getRange(rowIdx, 13).setValue(routeName);   // RouteName
  sheet.getRange(rowIdx, 17).setValue(reason);      // Reason
  sheet.getRange(rowIdx, 18).setValue(String(data.area || "").trim()); // Area
  sheet.getRange(rowIdx, 19).setValue(Math.max(0, parseInt(data.duration, 10) || 0)); // Duration

  if (currentStatus === ROUTE_STATUS.DRAFT && assignedTo) {
    sheet.getRange(rowIdx, 6).setValue(ROUTE_STATUS.ASSIGNED);
  }
  if (assignedTo && assignedTo !== previousAssignee) {
    try {
      notifyRoutineAssigned_(routineId, routeName, assignedTo, sheet.getRange(rowIdx, 15).getValue());
    } catch (e) {
      logError("notifyRoutineAssigned_:updateRoutine", e, { routineId: routineId });
    }
  }
  return { status: "ok" };
}


// Phase 1 — Reschedule: the contractor's engineer moves the due date, no
// approval needed. Keeps the very first due date (OriginalDueDate) and
// the latest reason/who/when on the row; Code.js writes each reschedule
// to the Activity log with both dates.
function rescheduleRoutine(ss, data) {
  var routineId = String(data.routineId || "").trim();
  if (!routineId) return { error: "routineId is required" };
  var reason = String(data.reason || "").trim();
  if (!reason) return { error: "A reason is required to reschedule" };
  var newDue = data.newDueDate ? new Date(data.newDueDate) : null;
  if (!newDue || isNaN(newDue.getTime())) return { error: "A valid new due date is required" };
  var sheet = ss.getSheetByName("ROUTINES");
  if (!sheet) return { error: "ROUTINES sheet not found" };
  var rowIdx = findRowIndex(sheet, [0], [routineId], dataStartRowFor("ROUTINES"));
  if (rowIdx === -1) return { error: "Routine not found" };
  var status = routineStatusAt_(sheet, rowIdx);
  if ([ROUTE_STATUS.CONFIRMED, ROUTE_STATUS.CANCELLED, ROUTE_STATUS.WAITING].indexOf(status) !== -1) {
    return { error: "A route that is " + status + " can't be rescheduled" };
  }
  var oldDue = sheet.getRange(rowIdx, 15).getValue();
  if (sameDay_(oldDue, newDue)) return { error: "The new date is the same as the current due date" };

  ensureRoutinePhase1Headers_(sheet);
  var original = sheet.getRange(rowIdx, 23).getValue();
  if (!original) sheet.getRange(rowIdx, 23).setValue(oldDue || "");
  sheet.getRange(rowIdx, 15).setValue(newDue);
  sheet.getRange(rowIdx, 24, 1, 3).setValues([[reason, data.actingUser || "", new Date()]]);
  return {
    status: "ok",
    oldDueDate: oldDue ? formatDateForEmail_(oldDue) : "(none)",
    newDueDate: formatDateForEmail_(newDue),
    reason: reason
  };
}


// Pause/Resume/Cancel (Routines tab improvement pass) — mirrors
// setRouteTemplateStatus's naming and shape for the recurring-template
// side, one function covering all three transitions since they're really
// one "change the workflow Status, with rules about which changes are
// allowed" operation. A paused/cancelled routine still has every checklist
// item it had before (OA_ROUTINE_ITEMS is untouched) — pausing/cancelling
// only ever changes ROUTINES' own Status column.
function setRoutineStatus(ss, data) {
  var routineId = String(data.routineId || "").trim();
  if (!routineId) return { error: "routineId is required" };
  var status = String(data.status || "").trim();
  if (["Paused", "Cancelled", "Assigned"].indexOf(status) === -1) {
    return { error: "status must be Paused, Cancelled, or Assigned (to resume)" };
  }
  var sheet = ss.getSheetByName("ROUTINES");
  if (!sheet) return { error: "ROUTINES sheet not found" };
  var rowIdx = findRowIndex(sheet, [0], [routineId], dataStartRowFor("ROUTINES"));
  if (rowIdx === -1) return { error: "Routine not found" };
  var currentStatus = routineStatusAt_(sheet, rowIdx);

  if (status === "Paused" && currentStatus !== ROUTE_STATUS.ASSIGNED && currentStatus !== ROUTE_STATUS.IN_PROGRESS) {
    return { error: "Only an Assigned or In Progress route can be paused" };
  }
  if (status === "Assigned" && currentStatus !== ROUTE_STATUS.PAUSED) {
    return { error: "Only a Paused route can be resumed" };
  }
  if (status === "Cancelled" && (currentStatus === ROUTE_STATUS.CONFIRMED || currentStatus === ROUTE_STATUS.CANCELLED)) {
    return { error: "A confirmed or already-cancelled route cannot be cancelled" };
  }
  // Resuming a route that never had a technician puts it back to Draft.
  if (status === "Assigned" && !String(sheet.getRange(rowIdx, 3).getValue() || "").trim()) {
    status = ROUTE_STATUS.DRAFT;
  }

  sheet.getRange(rowIdx, 6).setValue(status);
  return { status: "ok" };
}


// Admin-only hard delete (Routines tab improvement pass): distinct from
// setRoutineStatus's "Cancelled" — Cancel keeps the routine and its
// checklist around as a record of what was asked for and never done;
// this actually removes it, confirmed directly by the user as an Admin-
// only capability ("admin can delete routine not just cancelled"). Also
// removes every OA_ROUTINE_ITEMS row that belongs to it ("all related
// data will be deleted") — but deliberately NOT any real-world record a
// completed item already created elsewhere (an Oil Change LOG/Oil Top Up
// LOG entry, an in-app notification, an audit trail row): those document
// something that actually happened and stay true regardless of whether
// the routine that prompted them still exists, same reasoning
// deleteRouteTemplate never touches the routines a template already
// generated.
function deleteRoutine(ss, data) {
  var routineId = String(data.routineId || "").trim();
  if (!routineId) return { error: "routineId is required" };
  var routineSheet = ss.getSheetByName("ROUTINES");
  if (!routineSheet) return { error: "ROUTINES sheet not found" };
  var rowIdx = findRowIndex(routineSheet, [0], [routineId], dataStartRowFor("ROUTINES"));
  if (rowIdx === -1) return { error: "Routine not found" };
  routineSheet.deleteRow(rowIdx);

  var itemsSheet = ss.getSheetByName("OA_ROUTINE_ITEMS");
  if (itemsSheet) {
    var dataStart = dataStartRowFor("OA_ROUTINE_ITEMS");
    var vals = itemsSheet.getDataRange().getValues();
    // Delete bottom-to-top so each deleteRow() doesn't shift the index of
    // rows still waiting to be checked.
    for (var i = vals.length - 1; i >= dataStart - 1; i--) {
      if (String(vals[i][1] || "").trim() === routineId) itemsSheet.deleteRow(i + 1);
    }
  }
  return { status: "ok" };
}


function submitRoutineItem(ss, data) {
  var routineItemId = String(data.routineItemId || "").trim();
  if (!routineItemId) return { error: "routineItemId is required" };
  var sheet = ss.getSheetByName("OA_ROUTINE_ITEMS");
  if (!sheet) return { error: "OA_ROUTINE_ITEMS sheet not found" };
  var rowIdx = findRowIndex(sheet, [0], [routineItemId], dataStartRowFor("OA_ROUTINE_ITEMS"));
  if (rowIdx === -1) return { error: "Routine item not found" };

  // Phase 1: the checklist is open only while the route is with the
  // technician (Assigned / In Progress, including after a return).
  var parentId = String(sheet.getRange(rowIdx, 2).getValue() || "").trim();
  var parentSheet = ss.getSheetByName("ROUTINES");
  var parentIdx = parentSheet && parentId ? findRowIndex(parentSheet, [0], [parentId], dataStartRowFor("ROUTINES")) : -1;
  if (parentIdx !== -1) {
    var parentStatus = routineStatusAt_(parentSheet, parentIdx);
    if (parentStatus !== ROUTE_STATUS.ASSIGNED && parentStatus !== ROUTE_STATUS.IN_PROGRESS) {
      return { error: "This route is " + parentStatus + " — its checklist can't be changed now." };
    }
  }

  sheet.getRange(rowIdx, 6).setValue(data.implemented ? "Yes" : "No");
  sheet.getRange(rowIdx, 7).setValue(data.notImplementedReason || "");
  sheet.getRange(rowIdx, 8).setValue(data.actualDate || new Date());
  sheet.getRange(rowIdx, 9).setValue(data.actualQuantity || "");
  sheet.getRange(rowIdx, 10).setValue(data.sampleTaken ? "Yes" : "No");
  stampLastModified(sheet, "OA_ROUTINE_ITEMS", rowIdx);

  // The frontend's Routines list already has an "InProgress" status/badge,
  // but nothing ever set it — a routine sat as "Assigned" no matter how much
  // of its checklist was done, until the whole thing was Submitted. Flip it
  // the first time any item on it is saved, so the list reflects reality.
  var routineId = String(sheet.getRange(rowIdx, 2).getValue() || "").trim();
  if (routineId) {
    var routinesSheet = ss.getSheetByName("ROUTINES");
    if (routinesSheet) {
      var rIdx = findRowIndex(routinesSheet, [0], [routineId], dataStartRowFor("ROUTINES"));
      if (rIdx !== -1) {
        var currentStatus = routineStatusAt_(routinesSheet, rIdx);
        if (currentStatus === ROUTE_STATUS.ASSIGNED) {
          routinesSheet.getRange(rIdx, 6).setValue(ROUTE_STATUS.IN_PROGRESS);
        }
      }
    }
  }
  return { status: "ok" };
}


function submitRoutine(ss, data) {
  var routineId = String(data.routineId || "").trim();
  if (!routineId) return { error: "routineId is required" };
  var sheet = ss.getSheetByName("ROUTINES");
  if (!sheet) return { error: "ROUTINES sheet not found" };
  var rowIdx = findRowIndex(sheet, [0], [routineId], dataStartRowFor("ROUTINES"));
  if (rowIdx === -1) return { error: "Routine not found" };
  var current = routineStatusAt_(sheet, rowIdx);
  // Already sent (e.g. the same submit replayed from the offline queue).
  if (current === ROUTE_STATUS.WAITING || current === ROUTE_STATUS.CONFIRMED) return { status: "ok", unchanged: true };
  if (current !== ROUTE_STATUS.ASSIGNED && current !== ROUTE_STATUS.IN_PROGRESS) {
    return { error: "A route that is " + current + " can't be submitted" };
  }
  sheet.getRange(rowIdx, 6).setValue(ROUTE_STATUS.WAITING);
  sheet.getRange(rowIdx, 7).setValue(new Date());

  try {
    var routeName = sheet.getRange(rowIdx, 13).getValue();
    var contractor = sheet.getRange(rowIdx, 4).getValue();
    notifyRoutineSubmitted_(routineId, routeName, contractor, data.actingUser || "");
  } catch (e) {
    logError("notifyRoutineSubmitted_", e, { routineId: routineId });
  }

  return { status: "ok" };
}


function approveRoutine(ss, data) {
  var routineId = String(data.routineId || "").trim();
  if (!routineId) return { error: "routineId is required" };
  var sheet = ss.getSheetByName("ROUTINES");
  if (!sheet) return { error: "ROUTINES sheet not found" };
  var rowIdx = findRowIndex(sheet, [0], [routineId], dataStartRowFor("ROUTINES"));
  if (rowIdx === -1) return { error: "Routine not found" };
  var current = routineStatusAt_(sheet, rowIdx);
  if (current === ROUTE_STATUS.CONFIRMED) return { status: "ok", unchanged: true };
  if (current !== ROUTE_STATUS.WAITING) return { error: "Only a route Waiting Approval can be confirmed" };
  sheet.getRange(rowIdx, 6).setValue(ROUTE_STATUS.CONFIRMED);
  sheet.getRange(rowIdx, 8).setValue(data.approvedBy || data.actingUser || "");
  sheet.getRange(rowIdx, 9).setValue(new Date());

  try {
    var routeName = sheet.getRange(rowIdx, 13).getValue();
    var assignedTo = sheet.getRange(rowIdx, 3).getValue();
    notifyRoutineApproved_(routineId, routeName, assignedTo, data.approvedBy || data.actingUser || "");
  } catch (e) {
    logError("notifyRoutineApproved_", e, { routineId: routineId });
  }

  return { status: "ok" };
}


// Phase 1 — Return for correction: back to In Progress with a reason; the
// technician corrects and resubmits. The red "Returned" badge is shown
// while ReturnedDate is on/after SubmittedDate and the route is with the
// technician.
function returnRoutine(ss, data) {
  var routineId = String(data.routineId || "").trim();
  if (!routineId) return { error: "routineId is required" };
  var reason = String(data.reason || "").trim();
  if (!reason) return { error: "A reason is required to return a route" };
  var sheet = ss.getSheetByName("ROUTINES");
  if (!sheet) return { error: "ROUTINES sheet not found" };
  var rowIdx = findRowIndex(sheet, [0], [routineId], dataStartRowFor("ROUTINES"));
  if (rowIdx === -1) return { error: "Routine not found" };
  var current = routineStatusAt_(sheet, rowIdx);
  if (current !== ROUTE_STATUS.WAITING) return { error: "Only a route Waiting Approval can be returned" };

  ensureRoutinePhase1Headers_(sheet);
  sheet.getRange(rowIdx, 6).setValue(ROUTE_STATUS.IN_PROGRESS);
  sheet.getRange(rowIdx, 20, 1, 3).setValues([[reason, data.actingUser || "", new Date()]]);

  try {
    notifyRoutineReturned_(routineId, sheet.getRange(rowIdx, 13).getValue(), sheet.getRange(rowIdx, 3).getValue(), data.actingUser || "", reason);
  } catch (e) {
    logError("notifyRoutineReturned_", e, { routineId: routineId });
  }
  return { status: "ok" };
}


function addRoutineComment(ss, data) {
  var routineId = String(data.routineId || "").trim();
  if (!routineId) return { error: "routineId is required" };
  var sheet = ss.getSheetByName("ROUTINES");
  if (!sheet) return { error: "ROUTINES sheet not found" };
  var rowIdx = findRowIndex(sheet, [0], [routineId], dataStartRowFor("ROUTINES"));
  if (rowIdx === -1) return { error: "Routine not found" };
  sheet.getRange(rowIdx, 10).setValue(data.commentText || "");
  sheet.getRange(rowIdx, 11).setValue(data.commentBy || "");
  sheet.getRange(rowIdx, 12).setValue(new Date());
  return { status: "ok" };
}
