// GENERATED by scripts/gen-install-check.mjs — do not edit by hand.
//
// Install check: run checkInstall() from the Apps Script editor (pick it in
// the function list, then Run). The log lists every file of this project
// that is missing or out of date (some of its functions are not found), so
// a file pasted into the wrong place or only half pasted shows at once.
// After pasting fixes, publish a new version of the deployment.

var INSTALL_CHECK_FILES = {
  "Activity":["activityAllowed_","actIso_","actEquipmentDiff_","listPlatformActivity_","actUserEmail_"],
  "AdminSettings":["getSetting_","setSetting_","runScheduledBackup_","assertMinimumAdminsAfterDeactivation_","getPlatformHealth_","exportAllData_"],
  "Areas":["arKey_","arRead_","arClean_","getAreas_","arMachines_","maybeAppAdmin_","saveAreas_","arDiff_"],
  "AssetMaster":["amKey_","amRead_","amOrgs_","amOut_","listEquipmentMaster_","saveEquipmentMaster_","amLog_","listEquipmentLog_"],
  "Auth":["hashPassword_","generateSalt_","generateTempPassword_","createUser_","login_","changePassword_","adminResetPassword_"],
  "Code":["doPost","doGet"],
  "Config":["getSpreadsheetId_"],
  "EmailSettings":["emRead_","getEmailSettings_","saveEmailSettings_","emWrite_","emailAllowed_"],
  "Rbac":["hasPermission_","requirePermission_","getContractorScope_","requireAppAdmin_","seedRolePermissions_","runSeedRolePermissions","updateRolesPhase7","addContractorManagerRole"],
  "SampleTestUsers":["createSampleTestUsers_","resetSampleTestUserPasswords_"],
  "Session":["getSessionSecret_","base64UrlEncode_","base64UrlDecode_","signPayload_","issueSessionToken_","requireSession_"],
  "SettingsAccess":["saRank_","saClamp_","saSheet_","saRead_","saLevels_","requireSettingsEdit_","saCheck_","getSettingsAccess_","saveSettingsAccess_","saWrite_","platformLog_"],
  "Translations":["translationsSheet_","getTranslations_","addTranslationTerms_","saveTranslation_"],
  "Users":["listOrgUsers_","listRoles_","setUserRoles_"],
  "Utils":["jsonResponse_","ok_","safeHandle_","withLock_","withIdempotency_","getSheet_","readSheetAsObjects_","findRowByColumn_","appendRow_","deleteRowsByColumn_"]
};

function checkInstall() {
  var g = (function () { return this; })() || globalThis;
  var missing = [], old = [], ok = 0;
  Object.keys(INSTALL_CHECK_FILES).forEach(function (file) {
    var names = INSTALL_CHECK_FILES[file];
    var gone = names.filter(function (n) { return typeof g[n] !== 'function'; });
    if (gone.length === names.length) missing.push(file);
    else if (gone.length) old.push(file + ' (not found: ' + gone.slice(0, 5).join(', ') + (gone.length > 5 ? ' …' : '') + ')');
    else ok++;
  });
  var lines = ['platform-core: ' + ok + ' of ' + Object.keys(INSTALL_CHECK_FILES).length + ' files OK.'];
  if (missing.length) lines.push('MISSING — add these files: ' + missing.join(', '));
  if (old.length) lines.push('OUT OF DATE — paste these files again: ' + old.join('; '));
  if (!missing.length && !old.length) lines.push('Everything is in place. Remember to publish a new version of the deployment.');
  var text = lines.join('\n');
  Logger.log(text);
  return text;
}
